### ISSUE TITLE
closure support issue

### ISSUE THREAD

**Issue by inikishev** [ClashLuke/HeavyBall#10]
Hi!

This is code in "PrecondSchedulePaLMForeachSOAP"
```py
    @torch.no_grad()
    def step(self, closure=None):
        if closure is None:
            loss = None
        else:
            loss = closure()
```
it should be 
```py
    @torch.no_grad()
    def step(self, closure=None):
        if closure is None:
            loss = None
        else:
            with torch.enable_grad():
                loss = closure()
```
otherwise backward causes an error in the closure that element 0 of variables does not require grad and does not have a grad_fn

**Comment by ClashLuke** [comment]
Good catch! I was using the closure interface myself (through Lightning) and hadn't noticed that, though it seems to have obfuscated the issue.\
This is fixed in `0.15.0` with an accompanying test.
