### ISSUE TITLE
Use of `ckp1` in ScheduleFree util method deviates from reference implementation

### ISSUE THREAD

**Issue by LoganBooker** [ClashLuke/HeavyBall#13]
Was just having a poke around and noticed that the use of  `ckp1` in the helper method for ScheduleFree seems to be the inverse of what's in the reference implementation.

https://github.com/ClashLuke/HeavyBall/blob/e786b397755e8ad2b7c2203d4034f0582f2a7f61/heavyball/utils.py#L41-L50

The line in question:
https://github.com/ClashLuke/HeavyBall/blob/e786b397755e8ad2b7c2203d4034f0582f2a7f61/heavyball/utils.py#L45

Versus the [reference optimiser](https://github.com/facebookresearch/schedule_free/blob/0daa68b5fd6e26f5b79f5943dedefc54bc8ee93e/schedulefree/adamw_schedulefree.py#L179):
```
torch._foreach_lerp_(y, z, weight=ckp1)
```
I might have missed something and this is completely correct, but wanted to make sure there wasn't a different form of updating the states I may have missed.

**Comment by ClashLuke** [comment]
That is a very good point; I hadn't noticed that. Thank you for the detailed report!
