### ISSUE TITLE
bfloat16 support

### ISSUE THREAD

**Issue by felipemello1** [ClashLuke/HeavyBall#2]
I haven't looked into the code yet, but i imagine that it doesn't check for the dtype and upcast it to fp32

```
File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/heavyball/palm_foreach_soap.py", line 82, in step
    self.update_preconditioner(grad, state, max_precond_dim=group['max_precond_dim'],
  File "/home/felipemello/.conda/envs/torchtune/lib/python3.11/site-packages/heavyball/palm_foreach_soap.py", line 202, in update_preconditioner
    state['GG'][idx].lerp_(outer_product, 1 - state['shampoo_beta'])
RuntimeError: expected dtype float for `end` but got dtype c10::BFloat16
```

**Comment by ClashLuke** [comment]
Thank you for the report! Fixed in `0.3.1`\
However, be aware that the large preconditioner states (GG and Q) likely need float32 precision. So, I hardcoded the entire optimizer to be fp32. Without it, the SOAP calculations would fail (SOAP even upcasts to fp64 internally).

**Comment by felipemello1** [comment]
It makes a lot of sense to have the optimizer in full precision. I dont know what pytorch does with AdamW, but i imagine that they upcast the gradients during the step. Thanks for fixing it. Will give it another try next week.

**Comment by ClashLuke** [comment]
`0.7.0` contains stochastic rounding, which should improve convergence. Looking forward to your results!
