### ISSUE TITLE
SF .eval() switch

### ISSUE THREAD

**Issue by neosr-project** [ClashLuke/HeavyBall#21]
Hi, thanks for this amazing package.
Some questions:
1 - On official schedule-free, we need to switch to `.eval()` mode before model saving and before validation (inference). Is this required on HeavyBall implementation as well?
2 - Is there any way of disabling `compile()`?
3 - And any reason to [use python's RNG](https://github.com/ClashLuke/HeavyBall/blob/main/heavyball/precond_schedule_sfpsoap.py#L71) instead of torch Generator?
4 - ~~Looks like there's a recursion error in `PrecondScheduleSFPaLMSOAP`. It [calls `exp_avg_sq_`](https://github.com/ClashLuke/HeavyBall/blob/main/heavyball/precond_schedule_sfpsoap.py#L13), which in turn [calls `_compilable_exp_avg_sq_`](https://github.com/ClashLuke/HeavyBall/blob/main/heavyball/utils.py#L179).~~. It doesn't, but the name of the function is the same as the other one in utils.py, leading to confusion.

Thanks in advance.

**Comment by ClashLuke** [comment]
Hey, thank you for your interest.

1) Yes, you have to call `.eval()` and `.train()`. Those functions exist for all ScheduleFree optimizers.

2) Yes, this is documented in the readme. I will change it to show that `None` disables compile.
> `compile_mode`, a string passed as-is to `torch.compile(mode=compile_mode)` in all compiled heavyball calls

3) We need CPU values
