### ISSUE TITLE
[Feature Request] Optional adaptive gradient clipping

### ISSUE THREAD

**Issue by douglas-boubert** [ClashLuke/HeavyBall#3]
In version `0.4.0` the gradient clipping was only applied if `clip_val > 0`. Please can you add back in the option to not do the adaptive gradient clipping?

**Comment by ClashLuke** [comment]
Wow, that completely slipped my mind. Good catch, thank you! Fixed in `0.7.3`

**Comment by douglas-boubert** [comment]
That was amazingly fast, thank you!
