### ISSUE TITLE
[Possible Bug] First call of `_update_preconditioner` is much slower in `>=0.5.0` than in `0.4.0`

### ISSUE THREAD

**Issue by douglas-boubert** [ClashLuke/HeavyBall#4]
I am finding that the first round of calls to `_update_preconditioner` (within the `"z" not in state` logic) is much slower in `>=0.5.0` than in `0.4.0`. I have only checked `SFPaLMForeachSOAP`.

Is this expected behaviour?

**Comment by ClashLuke** [comment]
It definitely is, I should've documented that better. Thank you for the report!\
I've added an absolutely excessive amount of `torch.cuda.empty_cache()` to the first iteration to reduce peak memory usage, which spikes during the first init.\
Unfortunately, standard fallback logic doesn't seem to work well, as empty_cache() doesn't always remove all tensors when you're in an expect block.

Not sure what to do here.

**Comment by ClashLuke** [comment]
I've changed the logic to be less aggressive. Combined with the other memory access improvements, it's 3.4% faster with the same precond_every=2 schedule.

**Comment by ClashLuke** [comment]
Tested. Startup time is as low as expected.
I'd urgently recommend upgrading to `0.9.0`, as one of the internal einsums was incorrect in the previous versions, causing a severe regression for SOAP (not for Adam) compared to the baseline repository.

There are now tests to ensure the outputs won't stray too far. I'm working on adding regression tests (memory, runtime, loss) to ensure that things at least don't get worse when they have to be changed.

**Comment by douglas-boubert** [comment]
That initial start-up is a lot more manageable, thank you for the changes! I noticed that upgrading from `0.4.0` to later versions caused training runs with `SFPaLMForeachSOAP` to NaN in their first epoch - could that be related?
