### ISSUE TITLE
Duplicate `precond_update_prob_schedule`

### ISSUE THREAD

**Issue by francois-rozet** [ClashLuke/HeavyBall#6]
The following function overwrites the import of `precond_update_prob_schedule` from `utils`.

https://github.com/ClashLuke/HeavyBall/blob/443c67bbcbb9174ffbef97eb276324941a5ea879/heavyball/psgd_kron.py#L13-L32

**Comment by ClashLuke** [comment]
Excellent find, thank you! It's fixed in `0.12.6`
